### ISSUE TITLE
Gradient 

### ISSUE THREAD

**Issue by ryan-ellis** [gotechnica/technica-site-2019#17]
![image.png](https://images.zenhubusercontent.com/5b45198727aaa545cd301acb/7fdbd766-196a-483c-bd17-77d46b932c60)

**Comment by ryan-ellis** [comment]
Will probably need to implement on a component by component basis. Make sure the gradient looks good on mobile too.

**Comment by ryan-ellis** [comment]
reg:
#66A4B3 - #192E3A

faq:
#192E3A - #12202B

sponsors:
#12202B - #1C1F22

**Comment by dsmolyak** [comment]
Addressed by #56
